name: Grant Gibson
favicon: null
layout_spectrum: 0.9023461695760489
typography_spectrum: 0.4677043913397938
title: Grant Gibson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#0b0704'
    - '#67594e'
    - '#b0bec1'
    - '#d09d4e'
  brandStrength: 0.8277439267840236
  lightness: 0.3445271903183311
  saturation: 0.7960207571741194
  rhythmicContrast: 0.3445385782979429
purpose: []
