name: Grant Gibson
favicon: null
layout_spectrum: 0.9023461695760489
typography_spectrum: 0.4677043913397938
title: 'Grant Gibson, Canadian Entrepreneur | Businessman | Aviator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfc4fe'
    - '#7195e9'
    - '#516dc1'
    - '#2b468d'
    - '#000210'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
